spring.application.name=gestionalec

spring.datasource.url=jdbc:mysql://localhost:3306/gestionalec
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

#come mi comporto col database preesistente
spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret= siVisPacemParaBellumErrareHumanumEstPerseverareAutemDiabolicumAleaIactaEst
jwt.expiration=86400000
# 86400000 ms = 24 ore

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lorigiu2004@gmail.com
# App Password, NON la password Gmail normale
spring.mail.password=lwru qxfr tcol xffq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ── File Upload ──────────────────────────────────────────────────────────
file.upload-dir=uploads/documenti
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# ── WebSocket ─────────────────────────────────────────────────────────────
# Non strettamente necessario, ma lascia la porta aperta
spring.websocket.client.user-destination-prefix=/user
