spring.application.name=gestionalec

spring.datasource.url=jdbc:mysql://localhost:3306/gestionalec
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

#come mi comporto col database preesistente
spring.jpa.hibernate.ddl-auto=update

jwt.secret= siVisPacemParaBellumErrareHumanumEstPerseverareAutemDiabolicumAleaIactaEst
jwt.expiration=86400000
# 86400000 ms = 24 ore